version: '3.8'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: server
        volumes:
            - ./server:/usr/src/app
        ports:
            - '5000:5000'
        env_file:
            - ./config.env
        tty: true
        command: yarn start
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: client
        volumes:
            - ./client:/usr/src/app
        ports:
            - '3000:3000'
        tty: true
        command: yarn start
