ARG CONT_IMG_VER
FROM node:lts-alpine as server_builder

WORKDIR /usr/src/app

COPY /server/package.json /server/yarn.lock ./

RUN yarn

COPY server/. .

RUN yarn build

#================================================================

FROM node:lts-alpine
ENV CONT_IMG_VER=${CONT_IMG_VER:-v1.0.0}
WORKDIR /usr/src/app

COPY /server/package.json /server/yarn.lock ./

RUN yarn --prod

COPY --from=server_builder /usr/src/app/dist /usr/src/app/

EXPOSE 80

CMD ["yarn", "run", "prod" ]
