# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run.
on:
    push:
        tags:
            - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Get tag name
              uses: olegtarasov/get-tag@v2.1
            - name: Checkout to tag
              uses: actions/checkout@v2
              with:
                  ref: ${{ env.GIT_TAG_NAME }}
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  pull: true
                  push: true
                  no-cache: true
                  tags: |
                      kyles11/ts-express-todo:latest
                      kyles11/ts-express-todo:${{ env.GIT_TAG_NAME }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
